<?php

namespace AppBundle\Repository;

/**
 * sousCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sousCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
