# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.twig.user.globals.class: FrontBundle\Twig\Extension\MenuExtension
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    


    fos_user.user_checker:
      class: FOS\UserBundle\Security\UserChecker
      autowire: true 
     
    app_registration_listener:
      class: AppBundle\EventListner\RegistrationListener
      arguments: ['@router']
      tags:
        - { name: kernel.event_subscriber }
      autowire: true

    app.twig.menu.globals:
      class: FrontBundle\Twig\Extension\MenuExtension
      arguments: ["@doctrine.orm.entity_manager"]
      tags:
        - { name: twig.extension }  

    
    app.twig.time.globals:
      class: FrontBundle\Twig\Extension\TimeExtension
      tags:
        - { name: twig.extension } 