<?php

namespace FrontBundle\Repository;

/**
 * DecorationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecorationRepository extends \Doctrine\ORM\EntityRepository
{
}
