<?php

namespace FrontBundle\Repository;

/**
 * EnvironmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvironmentsRepository extends \Doctrine\ORM\EntityRepository
{
}
