<?php

namespace FrontBundle\Repository;

/**
 * TypeServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeServicesRepository extends \Doctrine\ORM\EntityRepository
{
}
