<?php

namespace FrontBundle\Repository;

/**
 * TypeEnvironmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEnvironmentRepository extends \Doctrine\ORM\EntityRepository
{
}
