<?php

namespace FrontBundle\Repository;

/**
 * TypeDecorationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDecorationRepository extends \Doctrine\ORM\EntityRepository
{
}
